//Product List
export const ONE_PRODUCT_REQUEST = 'ONE_PRODUCT_REQUEST'
export const ONE_PRODUCT_SUCCESS = 'ONE_PRODUCT_SUCCESS'
export const ONE_PRODUCT_ERROR = 'ONE_PRODUCT_ERROR'

export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_ERROR = 'ALL_PRODUCTS_ERROR'

export const FOUND_PRODUCT_REQUEST = 'FOUND_PRODUCT_REQUEST'
export const FOUND_PRODUCT_SUCCESS = 'FOUND_PRODUCT_SUCCESS'
export const FOUND_PRODUCT_ERROR = 'FOUND_PRODUCT_ERROR'

export const CLEAR_ERROR = 'CLEAR_ERROR'