export const REMOVE_ONE_FROM_HISTORY_SUCCESS = 'REMOVE_ONE_FROM_HISTORY_SUCCESS'
export const REMOVE_ONE_FROM_HISTORY_ERROR = 'REMOVE_ONE_FROM_HISTORY_ERROR'

export const HISTORY_LIST_REQUEST = 'HISTORY_LIST_REQUEST'
export const HISTORY_LIST_SUCCESS = 'HISTORY_LIST_SUCCESS'
export const HISTORY_LIST_ERROR = 'HISTORY_LIST_ERROR'