export const PUBLISH_PRODUCT_SUCCESS = 'PUBLISH_PRODUCT_SUCCESS'
export const PUBLISH_PRODUCT_ERROR = 'PUBLISH_PRODUCT_ERROR'

export const MY_PRODUCTS_REQUEST = 'MY_PRODUCTS_REQUEST'
export const MY_PRODUCTS_SUCCESS = 'MY_PRODUCTS_SUCCESS'
export const MY_PRODUCTS_ERROR = 'MY_PRODUCTS_ERROR'

export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'

export const CLEAR_ERROR = 'CLEAR_ERROR'