//Product Actions

export const SAVE_PRODUCT_REQUEST = 'SAVE_PRODUCT_REQUEST'
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS'
export const SAVE_PRODUCT_ERROR = 'SAVE_PRODUCT_ERROR'

export const REMOVE_SAVED_SUCCESS = 'REMOVE_SAVED_SUCCESS'
export const REMOVE_SAVED_ERROR = 'REMOVE_SAVED_ERROR'

export const RATE_ONE_REQUEST = 'RATE_ONE_REQUEST'
export const RATE_ONE_SUCCESS = 'RATE_ONE_SUCCESS'
export const RATE_ONE_ERROR = 'RATE_ONE_ERROR'

export const AVERAGE_RATING_SUCCESS = 'AVERAGE_RATING_SUCCESS'
export const AVERAGE_RATING_ERROR = 'AVERAGE_RATING_ERROR'

//Product List

export const SAVED_PRODUCTS_REQUEST = 'SAVED_PRODUCTS_REQUEST'
export const SAVED_PRODUCTS_SUCCESS = 'SAVED_PRODUCTS_SUCCESS'
export const SAVED_PRODUCTS_ERROR = 'SAVED_PRODUCTS_ERROR'

export const RATED_PRODUCTS_REQUEST = 'RATED_PRODUCTS_REQUEST'
export const RATED_PRODUCTS_SUCCESS = 'RATED_PRODUCTS_SUCCESS'
export const RATED_PRODUCTS_ERROR = 'RATED_PRODUCTS_ERROR'

export const ONE_PRODUCT_REQUEST = 'ONE_PRODUCT_REQUEST'
export const ONE_PRODUCT_SUCCESS = 'ONE_PRODUCT_SUCCESS'
export const ONE_PRODUCT_ERROR = 'ONE_PRODUCT_ERROR'

export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_ERROR = 'ALL_PRODUCTS_ERROR'

export const FOUND_PRODUCT_REQUEST = 'FOUND_PRODUCT_REQUEST'
export const FOUND_PRODUCT_SUCCESS = 'FOUND_PRODUCT_SUCCESS'
export const FOUND_PRODUCT_ERROR = 'FOUND_PRODUCT_ERROR'

export const RATED_LIST_REQUEST = 'RATED_LIST_REQUEST'
export const RATED_LIST_SUCCESS = 'RATED_LIST_SUCCESS'
export const RATED_LIST_ERROR = 'RATED_LIST_ERROR'

export const CLEAR_ERROR = 'CLEAR_ERROR'