export const RATE_ONE_REQUEST = 'RATE_ONE_REQUEST'
export const RATE_ONE_SUCCESS = 'RATE_ONE_SUCCESS'
export const RATE_ONE_ERROR = 'RATE_ONE_ERROR'

export const AVERAGE_RATING_SUCCESS = 'AVERAGE_RATING_SUCCESS'
export const AVERAGE_RATING_ERROR = 'AVERAGE_RATING_ERROR'

export const RATED_PRODUCTS_REQUEST = 'RATED_PRODUCTS_REQUEST'
export const RATED_PRODUCTS_SUCCESS = 'RATED_PRODUCTS_SUCCESS'
export const RATED_PRODUCTS_ERROR = 'RATED_PRODUCTS_ERROR'

export const RATED_LIST_REQUEST = 'RATED_LIST_REQUEST'
export const RATED_LIST_SUCCESS = 'RATED_LIST_SUCCESS'
export const RATED_LIST_ERROR = 'RATED_LIST_ERROR'

export const CLEAR_ERROR = 'CLEAR_ERROR'