export const SAVE_PRODUCT_REQUEST = 'SAVE_PRODUCT_REQUEST'
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS'
export const SAVE_PRODUCT_ERROR = 'SAVE_PRODUCT_ERROR'

export const REMOVE_SAVED_SUCCESS = 'REMOVE_SAVED_SUCCESS'
export const REMOVE_SAVED_ERROR = 'REMOVE_SAVED_ERROR'

export const SAVED_PRODUCTS_LIST_REQUEST = 'SAVED_PRODUCTS_LIST_REQUEST'
export const SAVED_PRODUCTS_LIST_SUCCESS = 'SAVED_PRODUCTS_LIST_SUCCESS'
export const SAVED_PRODUCTS_LIST_ERROR = 'SAVED_PRODUCTS_LIST_ERROR'

export const CLEAR_ERROR = 'CLEAR_ERROR'