export const MY_PROFILE_REQUEST = 'MY_PROFILE_REQUEST'
export const MY_PROFILE_SUCCESS = 'MY_PROFILE_SUCCESS'
export const MY_PROFILE_ERROR = 'MY_PROFILE_ERROR'

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR'

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'

export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR'

export const CLEAR_ERROR = 'CLEAR_ERROR'